# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rust_fun_wrappers", use_symbols = TRUE, package_name = "rust.fun")

#' @usage NULL
#' @useDynLib rust.fun, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @export
standardise_strings <- function(input, to_uppercase, trim_whitespace, remove_double_spaces) .Call(wrap__standardise_strings, input, to_uppercase, trim_whitespace, remove_double_spaces)

#' @export
r_format_cdate <- function(date_vec, date_format) .Call(wrap__r_format_cdate, date_vec, date_format)

#' @export
r_format_date <- function(date_vec, date_format) .Call(wrap__r_format_date, date_vec, date_format)


# nolint end
