# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rust_fun_wrappers", use_symbols = TRUE, package_name = "rust.fun")

#' @usage NULL
#' @useDynLib rust.fun, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @export
standardise_strings <- function(input, to_uppercase, trim_whitespace, remove_double_spaces) .Call(wrap__standardise_strings, input, to_uppercase, trim_whitespace, remove_double_spaces)

#' @export
r_format_cdate <- function(date_vec, date_format) .Call(wrap__r_format_cdate, date_vec, date_format)

#' @export
r_format_date <- function(date_vec, date_format) .Call(wrap__r_format_date, date_vec, date_format)

#' @export
compute_damerau_levenshtein_distance <- function(strs1, strs2) .Call(wrap__compute_damerau_levenshtein_distance, strs1, strs2)

compute_levenshtein_distance <- function(strs1, strs2) .Call(wrap__compute_levenshtein_distance, strs1, strs2)

compute_jaro_winkler_distance <- function(strs1, strs2, winklerize) .Call(wrap__compute_jaro_winkler_distance, strs1, strs2, winklerize)

compute_hamming_distance <- function(strs1, strs2) .Call(wrap__compute_hamming_distance, strs1, strs2)

#' @export
match_vector <- function(pattern, strings) .Call(wrap__match_vector, pattern, strings)

list_files <- function(dir) .Call(wrap__list_files, dir)


# nolint end
